name: 'Run Jest'
description: 'Run jest unit test and generate report'
inputs:
  github-token:
    required: true
    description: 'A github access token'
    default: ${{ github.token }}
runs:
  using: 'node16'
  main: 'dist/index.js'